"""add reference data tables

Revision ID: 3aff01c879df
Revises: 3ff80baf1219
Created: 2026-09-22 10:42:17.832062+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3aff01c879df"
down_revision: str | None = "3ff80baf1219"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("band", sa.String(), nullable=False),
        sa.Column("planned_calls", sa.Integer(), nullable=False),
        sa.Column("expected_score", sa.Float(), nullable=True),
        sa.Column("score_variance", sa.Float(), nullable=True),
        sa.Column("dominant_pattern", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
    )
    with op.batch_alter_table("agents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agents_reference"), ["reference"], unique=True)

    op.create_table(
        "brokers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("agency", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("groups_in_book", sa.Integer(), nullable=False),
        sa.Column("signal_profile", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brokers")),
    )
    with op.batch_alter_table("brokers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_brokers_reference"), ["reference"], unique=True)

    op.create_table(
        "rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(), nullable=False),
        sa.Column("layer", sa.String(), nullable=False),
        sa.Column("area", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("commonly_confused_with", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("confidence", sa.String(), nullable=False),
        sa.Column("call_scenarios", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rules")),
    )
    with op.batch_alter_table("rules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rules_reference"), ["reference"], unique=True)

    op.create_table(
        "touchpoints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(), nullable=False),
        sa.Column("owner", sa.String(), nullable=False),
        sa.Column("controls", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_touchpoints")),
    )
    with op.batch_alter_table("touchpoints", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_touchpoints_reference"), ["reference"], unique=True)

    op.create_table(
        "employers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("industry", sa.String(), nullable=False),
        sa.Column("design_churn_profile", sa.String(), nullable=False),
        sa.Column("eligible", sa.Integer(), nullable=False),
        sa.Column("enrolled", sa.Integer(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("renewal_month", sa.String(), nullable=False),
        sa.Column("broker_id", sa.Integer(), nullable=False),
        sa.Column("dental_sponsorship", sa.String(), nullable=False),
        sa.Column("lines_held", sa.String(), nullable=False),
        sa.Column("planned_calls", sa.Integer(), nullable=False),
        sa.Column("planned_member_calls", sa.Integer(), nullable=False),
        sa.Column("planned_employer_calls", sa.Integer(), nullable=False),
        sa.Column("participation", sa.Float(), nullable=True),
        sa.Column("fee_band", sa.Integer(), nullable=False),
        sa.Column("annual_fee", sa.Integer(), nullable=False),
        sa.Column("annual_premium", sa.Float(), nullable=True),
        sa.Column("cobra_regime", sa.String(), nullable=False),
        sa.Column("calls_per_100", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["broker_id"], ["brokers.id"], name=op.f("fk_employers_broker_id_brokers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employers")),
    )
    with op.batch_alter_table("employers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_employers_reference"), ["reference"], unique=True)

    op.create_table(
        "employer_contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("authority", sa.String(), nullable=False),
        sa.Column("employer_id", sa.Integer(), nullable=False),
        sa.Column("planned_calls", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employer_id"],
            ["employers.id"],
            name=op.f("fk_employer_contacts_employer_id_employers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employer_contacts")),
    )
    with op.batch_alter_table("employer_contacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_employer_contacts_reference"), ["reference"], unique=True
        )

    op.create_table(
        "members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("employer_id", sa.Integer(), nullable=False),
        sa.Column("primary_line", sa.String(), nullable=False),
        sa.Column("planned_calls", sa.Integer(), nullable=False),
        sa.Column("repeat_caller", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employer_id"], ["employers.id"], name=op.f("fk_members_employer_id_employers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_members")),
    )
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_members_reference"), ["reference"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_members_reference"))

    op.drop_table("members")
    with op.batch_alter_table("employer_contacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_employer_contacts_reference"))

    op.drop_table("employer_contacts")
    with op.batch_alter_table("employers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_employers_reference"))

    op.drop_table("employers")
    with op.batch_alter_table("touchpoints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_touchpoints_reference"))

    op.drop_table("touchpoints")
    with op.batch_alter_table("rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rules_reference"))

    op.drop_table("rules")
    with op.batch_alter_table("brokers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_brokers_reference"))

    op.drop_table("brokers")
    with op.batch_alter_table("agents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agents_reference"))

    op.drop_table("agents")
    # ### end Alembic commands ###
