"""add calls, call turns and ingest jobs tables

Revision ID: cc2958ed595c
Revises: 3aff01c879df
Created: 2026-09-22 11:42:39.737294+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cc2958ed595c"
down_revision: str | None = "3aff01c879df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingest_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("result_call_reference", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_jobs")),
    )
    op.create_table(
        "calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=True),
        sa.Column("aht_seconds", sa.Integer(), nullable=True),
        sa.Column("caller_type", sa.String(), nullable=False),
        sa.Column("caller_ref", sa.String(), nullable=False),
        sa.Column("agent_ref", sa.String(), nullable=False),
        sa.Column("resolution_status", sa.String(), nullable=False),
        sa.Column("resolution_reason", sa.String(), nullable=True),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("employer_contact_id", sa.Integer(), nullable=True),
        sa.Column("employer_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["employer_contact_id"],
            ["employer_contacts.id"],
            name=op.f("fk_calls_employer_contact_id_employer_contacts"),
        ),
        sa.ForeignKeyConstraint(
            ["employer_id"], ["employers.id"], name=op.f("fk_calls_employer_id_employers")
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_calls_member_id_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calls")),
    )
    with op.batch_alter_table("calls", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_calls_reference"), ["reference"], unique=True)

    op.create_table(
        "call_turns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("call_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_id"], ["calls.id"], name=op.f("fk_call_turns_call_id_calls")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_call_turns")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("call_turns")
    with op.batch_alter_table("calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_calls_reference"))

    op.drop_table("calls")
    op.drop_table("ingest_jobs")
    # ### end Alembic commands ###
