"""add stage cache entries

Revision ID: 6adb65d95809
Revises: cc2958ed595c
Created: 2026-09-23 04:53:00.619291+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6adb65d95809"
down_revision: str | None = "cc2958ed595c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stage_cache_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transcript_hash", sa.String(), nullable=False),
        sa.Column("layer", sa.String(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("output_text", sa.String(), nullable=False),
        sa.Column("cached_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_cache_entries")),
        sa.UniqueConstraint(
            "transcript_hash", "layer", "prompt_version", "model", name="uq_stage_cache_key"
        ),
    )
    with op.batch_alter_table("stage_cache_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stage_cache_entries_transcript_hash"), ["transcript_hash"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stage_cache_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stage_cache_entries_transcript_hash"))

    op.drop_table("stage_cache_entries")
    # ### end Alembic commands ###
