/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report application and dependency health */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import the workbook's reference (master-data) sheets */
        post: operations["import_reference_data_api_v1_reference_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ComponentHealthResponse */
        ComponentHealthResponse: {
            /** Detail */
            detail?: string | null;
            /** Name */
            name: string;
            status: components["schemas"]["ComponentStatus"];
        };
        /**
         * ComponentStatus
         * @description Outcome of probing a single component.
         * @enum {string}
         */
        ComponentStatus: "up" | "down";
        /** HealthResponse */
        HealthResponse: {
            /** Application */
            application: string;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Components */
            components?: components["schemas"]["ComponentHealthResponse"][];
            /** Environment */
            environment: string;
            status: components["schemas"]["ComponentStatus"];
            /** Version */
            version: string;
        };
        /** ImportCountsResponse */
        ImportCountsResponse: {
            /** Agents */
            agents: number;
            /** Brokers */
            brokers: number;
            /** Employer Contacts */
            employer_contacts: number;
            /** Employers */
            employers: number;
            /** Members */
            members: number;
            /** Rules */
            rules: number;
            /** Touchpoints */
            touchpoints: number;
        };
        /** ImportReferenceResponse */
        ImportReferenceResponse: {
            counts: components["schemas"]["ImportCountsResponse"];
            /** Warnings */
            warnings: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description A component is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    import_reference_data_api_v1_reference_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReferenceResponse"];
                };
            };
        };
    };
}
